# Generated by Django 5.0.3 on 2024-05-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
