# Generated by Django 5.0.3 on 2024-05-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_key',
            field=models.CharField(default='AABB00', max_length=8),
        ),
    ]
