# Generated by Django 5.0.3 on 2024-05-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_key',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
