# Generated by Django 5.0.3 on 2024-05-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_key',
            field=models.CharField(default='AABB00', max_length=8),
        ),
    ]
