# Generated by Django 5.0.3 on 2024-06-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=5),
        ),
    ]
