# Generated by Django 5.0.3 on 2024-06-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_solicitud_solicituditem_solicitud_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='user_key',
            field=models.CharField(default='AABB00', max_length=8),
        ),
    ]
